---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-backup-pvc
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: mariadb-backup
spec:
  schedule: "* * * * *"  # Runs daily at 08:00, 12:00, and 18:00
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup
            image: tanzu-harbor.pngd.gob.pe/mef-ped-prod/mariadb:10.6
            command:
            - /bin/sh
            - -c
            - |
              set -ex
              DATE=$(date +%Y%m%d-%H%M%S)
              echo "Backing up MariaDB to /backup/vaultwarden-backup-${DATE}.sql.gz"
              mysqldump -h mariadb-galera-client -u root -p${MYSQL_ROOT_PASSWORD} --databases vaultwarden --single-transaction > /backup/vaultwarden-backup-${DATE}.sql
              echo "Compressing backup"
              gzip /backup/vaultwarden-backup-${DATE}.sql
              echo "Deleting backups older than 30 days"
              find /backup -name "vaultwarden-backup-*.sql.gz" -mtime +30 -exec rm {} \;
              echo "Done"
            env:
            - name: TZ
              value: "America/Lima"
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-galera-secret
                  key: mysql-root-password
            volumeMounts:
            - name: backup-volume
              mountPath: /backup
          restartPolicy: OnFailure
          volumes:
          - name: backup-volume
            persistentVolumeClaim:
              claimName: mariadb-backup-pvc
