################################################################################
# Archivo de Configuración para Despliegue de MariaDB Galera HA
# Ejemplo de uso múltiple para diferentes entornos
################################################################################

# Información del deployment
deployment:
  name: mariadb-galera-prod           # Nombre único del deployment
  namespace: database-prod            # Namespace donde se desplegará
  chartVersion: latest                # Versión del chart de Bitnami (opcional)

debug:
  enabled: true

# Configuración de Storage
storage:
  autoGenerate: true                  # Generar automáticamente un StorageClass `<deployment>-<namespace>-sc`
  className: ""                       # Nombre personalizado (solo si autoGenerate=false)
  size: 50Gi                          # Tamaño del volumen
  cleanupBeforeDeploy: true           # Limpiar PVC/PV/StorageClass previos antes de desplegar
  
  # Configuración NFS
  nfs:
    server: pcmvsanfs01.pngd.gob.pe   # IP o hostname del servidor NFS
    path: /vsanfs/PROMETHEUS          # Ruta base en el servidor NFS
    autoSubPath: true                 # Crear subdirectorio automático por deployment+namespace
    subPath: ""                       # Subdirectorio manual (solo si autoSubPath=false)

# Credenciales (usar secretos seguros en producción)
credentials:
  rootPassword: "SuperSecureRootPass123!"
  username: "wso2carbon"
  password: "SecureUserPass456!"
  database: "WSO2AM_DB"
  backupPassword: "BackupPass789!"

# Configuración del Registry
registry:
  url: "tanzu-harbor.pngd.gob.pe/pcm"
  pullSecret: "harbor-registry-secret"
  createPullSecret: true
  credentials:
    username: "admin"
    password: "Opd$3rt12022$.2023$"
    email: "harbor@example.com"
  repository: "mariadb-galera"
  metricsRepository: "mysqld-exporter"
  volumePermissionsRepository: "os-shell"
  tag: "12.0.2-debian-12-r0"
  metricsTag: "0.17.2-debian-12-r16"
  volumePermissionsTag: "12-debian-12-r27"

# Configuración de Alta Disponibilidad
ha:
  replicaCount: 3                     # Número de réplicas (mínimo 3 para HA)
  minAvailable: 2                     # Pods mínimos disponibles durante updates

# Recursos
resources:
  requests:
    cpu: "1000m"                      # CPU request
    memory: "4Gi"                     # Memoria request
  limits:
    cpu: "2000m"                      # CPU limit
    memory: "8Gi"                     # Memoria limit

# Configuración de Backups
backup:
  enabled: true                       # Habilitar backups automáticos
  schedule: "0 2 * * *"               # Cron schedule (2 AM diario)
  retention: 7                        # Días de retención de backups

# Opciones de limpieza para uninstall-mariadb-ha.sh
cleanup:
  deleteDataPVCs: true                # Eliminar PVCs de datos del cluster
  deleteNamespace: false              # Eliminar namespace completo
  deleteStorageClass: true            # Eliminar StorageClass creado
  deletePullSecret: true              # Eliminar pull secret creado automáticamente
  force: false                        # Saltar confirmación interactiva
