apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-restore-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-static
  nfs:
    server: 10.9.9.27  # Reemplázalo con la IP de tu servidor NFS
    path: /mnt/pngd_vaultwarden  # Ruta fija en NFS
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-restore-pvc
spec:
  storageClassName: nfs-static
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: mariadb-restore
spec:
  schedule: "*/12 * * * *"  # Runs every 10 minutes
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: restore
            image: mariadb:10.6  # Same as backup image
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - |
              set -ex

              echo "Finding latest backup..."
              LATEST_BACKUP=$(ls -t /backup/vaultwarden-backup-*.sql.gz 2>/dev/null | head -1)

              # Verificar si LATEST_BACKUP está vacío
              if [ -z "$LATEST_BACKUP" ]; then
                echo "No backup file found! Exiting..."
                exit 1
              fi

              echo "Dropping existing database (if any)..."
              mysql -h mariadb-galera-client -u root -p${MYSQL_ROOT_PASSWORD} -e "DROP DATABASE IF EXISTS vaultwarden;" || true

              echo "Restoring $LATEST_BACKUP..."
              zcat "$LATEST_BACKUP" | mysql -h mariadb-galera-client -u root -p${MYSQL_ROOT_PASSWORD}

              echo "Restore complete!"
            env:
            - name: TZ
              value: "America/Lima"
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-galera-secret
                  key: mysql-root-password
            volumeMounts:
            - name: backup-volume
              mountPath: /backup
          restartPolicy: OnFailure
          volumes:
          - name: backup-volume
            persistentVolumeClaim:
              claimName: mariadb-restore-pvc  # Same PVC as backups
